export const menu = [
	{
		id: 1,
		category: "Coffee",
		name: "Espresso",
		img: "../tosta/images/menu/espresso.jpg",
		description: "Rich and bold, straight-up shot.",
		price: "$2.50",
	},
	{
		id: 2,
		category: "Coffee",
		name: "Americano",
		img: "../tosta/images/menu/americano.jpg",
		description: "Espresso with hot water.",
		price: "$3.00",
	},
	{
		id: 3,
		category: "Specialty Drinks",
		name: "Vanilla Cold Brew",
		img: "../tosta/images/menu/vanilla-cold-brew.jpg",
		description: "Cold brewed with a splash of vanilla cream.",
		price: "$4.25",
	},
	{
		id: 4,
		category: "Pastries",
		name: "Almond Croissant",
		img: "../tosta/images/menu/almond-croissant.jpg",
		description: "Flaky, buttery, filled with almond cream.",
		price: "$3.25",
	},
	{
		id: 5,
		category: "Coffee",
		name: "Latte",
		img: "../tosta/images/menu/latte.jpg",
		description: "Espresso with steamed milk.",
		price: "$3.75",
	},
	{
		id: 6,
		category: "Specialty Drinks",
		name: "Mocha",
		img: "../tosta/images/menu/mocha.jpg",
		description: "Espresso, chocolate, and steamed milk.",
		price: "$4.00",
	},
	{
		id: 7,
		category: "Specialty Drinks",
		name: "Matcha Latte",
		img: "../tosta/images/menu/mocha-latte.jpg",
		description: "Smooth matcha with almond milk.",
		price: "$4.50",
	},
	{
		id: 8,
		category: "Pastries",
		name: "Banana Bread",
		img: "../tosta/images/menu/banana-bread.jpg",
		description: "Soft and moist with a cinnamon crust.",
		price: "$2.75",
	},
	{
		id: 9,
		category: "Pastries",
		name: "Blueberry Muffin",
		img: "../tosta/images/menu/blueberry-muffin.jpg",
		description: "Fresh blueberries with a sugar top.",
		price: "$2.50",
	},
];
